steps:
  - name: "node:10.16.3"
    id: root-install
    entrypoint: npm
    args: ["install"]
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-create-profile
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/create-profile/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-delete-profile
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/delete-profile/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-query-profile
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/query-profile/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-update-profile
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/update-profile/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-provider-create-notification-processor
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/provider-create-notification-processor/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-provider-delete-notification-processor
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/provider-delete-notification-processor/cloudbuild.yaml
      wait