npm install
cd ./src/services/create-profile
npm install
cd ../delete-profile
npm install
cd ../query-profile
npm install
cd ../update-profile
npm install
cd ../provider-create-notification-processor
npm install
cd ../provider-delete-notification-processor
npm install